[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/admin"
  to = "/admin"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/admin-login"
  status = 200

[build.environment]
  NODE_VERSION = "18"
